### ISSUE TITLE
UI is updated with better look

### ISSUE THREAD

**Issue by ashwinikumar01** [Suvoo/NewsIndia_App#8]
**Earlier**
![Annotation 2020-10-25 001341](https://user-images.githubusercontent.com/69667369/97091209-db2c2000-1657-11eb-8a2e-ba1a7d3ee2eb.jpg)

**Updated**
![Annotation 2020-10-25 001509](https://user-images.githubusercontent.com/69667369/97091219-e8e1a580-1657-11eb-98a1-fe3e4d975f90.jpg)

Have a look for both screen and now its looking quite responsive and nice as user can understand where the news are divided
from and where the title are.

**Comment by ashwinikumar01** [comment]
@Suvoo Can you update me further?

**Comment by Suvoo** [comment]
Yea, thanks it will be merged
